services:
  db:
    image: docker.io/library/mysql:8.0
    container_name: piepydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piepydb

    volumes:
      - dbdata:/var/lib/mysql

  app:
    build: .
    image: piepyimage
    container_name: piepyapp
    tty: true
    environment:
      DB_URL: mysql+pymysql://root:root@db:3306/piepydb
      ASYNC_DB_URL: mysql+aiomysql://root:root@db:3306/piepydb
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata: